### ISSUE TITLE
DefinitelyType ZingChart Angular - Unable to find option in tooltip & rules

### ISSUE THREAD

**Issue by niravIntentlabs** [zingchart/zingchart-angular#11]
I am trying to use type definition of zing chart from https://github.com/zingchart/zingchart-angular/blob/master/projects/zingchart-angular/src/zingchart.d.ts

There are few option that I am not able to find it and that is giving a compilation error.

- **Unable to find "'html-mode': boolean" option in tooltip .**  
![image](https://user-images.githubusercontent.com/36921793/134052968-4136ba8c-2ae3-42a3-b89e-70b75961cd3f.png)

- **Rules array is missing in value box**
![image](https://user-images.githubusercontent.com/36921793/134053081-75f4ced9-112f-4d6c-8562-5d259a857024.png)
https://www.zingchart.com/docs/tutorials/elements/value-boxes

- Text & visible property is not present in rules array. 
![image](https://user-images.githubusercontent.com/36921793/134053664-ccb7ab3d-24e4-4261-b18d-bcae189ac5e3.png)

**Comment by niravIntentlabs** [comment]
Dear @zingsoftadmin , Polite kick

**Comment by stuurman** [comment]
@zingsoftadmin Is there already a solution for this? the comment is more than half a year old.

**Comment by stuurman** [comment]
@zingsoftadmin is there customer support on angular? this is more than half a year ago.

**Comment by jeanettephung** [comment]
Sorry about this. I will look into this issue and reply when its fixed.

You can always reach us at www.zingchart.com and either submit it under the "Contact" page or send us a message in the chat widget.

Best,
ZingSoft Team

**Comment by jeanettephung** [comment]
The definitions have been added.
Thank you for your patience.

Best,
ZingSoft Team

**Comment by niravIntentlabs** [comment]
Thank you @jeanettephung & @stuurman
