### ISSUE TITLE
DefinitelyType ZingChart Angular - Unable to add multiple items in Scale Y items Array

### ISSUE THREAD

**Issue by niravIntentlabs** [zingchart/zingchart-angular#25]
- Unable to find border radius property in items
![image (33)](https://user-images.githubusercontent.com/36921793/163742975-3539114f-8d14-42e9-831e-e62a6652d926.png)

- I am able to add only one item but need to add multiple scale Y items.
![image (32)](https://user-images.githubusercontent.com/36921793/163743012-ea8ed22d-8b90-49a0-ace2-fbc50aba137e.png)
![image (31)](https://user-images.githubusercontent.com/36921793/163743016-a5812d1c-fa86-4d20-9c7f-79113cfa8608.png)

**Comment by jeanettephung** [comment]
The TDF is now updated.
