### ISSUE TITLE
DefinitelyType ZingChart Angular - Few more properties are missing in Preview, tooltip & Scale Y

### ISSUE THREAD

**Issue by niravIntentlabs** [zingchart/zingchart-angular#26]
- visible property is missing in Preview.
![Screenshot from 2022-04-25 19-39-09](https://user-images.githubusercontent.com/36921793/165106797-bd5c8e7c-fe47-484e-bf5b-78f81cf5784b.png)

- rules array is missing in tooltip.
![Screenshot from 2022-04-25 19-39-28](https://user-images.githubusercontent.com/36921793/165106881-464f369e-5342-42bc-ae24-a848ccd1fa9e.png)

- ItemsOverlap is missing in ScaleX.
![Screenshot from 2022-04-25 19-40-17](https://user-images.githubusercontent.com/36921793/165107037-470bc16a-6068-4a31-81fe-9b77a86657b6.png)

**Comment by jeanettephung** [comment]
The properties are now added. Thank you for reporting these missing properties.
