### ISSUE TITLE
DefinitelyType ZingChart Angular - Properties are missing for rules.

### ISSUE THREAD

**Issue by niravIntentlabs** [zingchart/zingchart-angular#27]
1. rules inside plot - Missing properties are text, visible.
![Screenshot from 2022-04-26 07-28-51](https://user-images.githubusercontent.com/36921793/165205379-a4e43b35-20d8-41fe-8162-2a05a1050290.png)

2. rules inside tooltip - Missing properties are text, visible.
![Screenshot from 2022-04-26 07-28-31](https://user-images.githubusercontent.com/36921793/165205373-8f7fac92-a7bd-4498-9abe-36981e8304db.png)

3. To create a mix types of charts, Require a values property in graphset. This is also missing.
![Screenshot from 2022-04-26 07-28-15](https://user-images.githubusercontent.com/36921793/165205352-9d9199ed-d427-42da-bdba-32144e85fe45.png)

**Comment by jeanettephung** [comment]
Hi there,

The missing properties have been addressed.
Thank you for reporting them to us.

Best,
ZingSoft Team
