### ISSUE TITLE
Zing Chart Angular Peer Deps

### ISSUE THREAD

**Issue by babackkh** [zingchart/zingchart-angular#38]
why don't you update deps to newer versions and Ivy engine? it's been a very long time and you're just releasing minor updates. I'm using Angular 14 in production and I have many problems during CI and build process just because of conflicting peer dependencies of zingchart angular. please reconsider

**Comment by Cateye82** [comment]
We made the same experience. Looking forward to some major updates.

**Comment by jeanettephung** [comment]
Wrapper is now compatible with Angular 16
