### ISSUE TITLE
Type Definition of zing chart - Unable to find few options

### ISSUE THREAD

**Issue by niravIntentlabs** [zingchart/zingchart-angular#5]
I am trying to use type definition of  zing chart from https://github.com/zingchart/zingchart-angular/blob/master/projects/zingchart-angular/src/zingchart.d.ts

There are few option that I am not able to find it and that is giving a compilation error.

- In 'scale-y' unable to add multiple items.

![Screenshot from 2021-02-04 18-21-22](https://user-images.githubusercontent.com/36921793/106895442-3a4d0680-6716-11eb-85d3-f830f47eb55e.png)

- In behavior- unable to add multiple behavior option.  

![Screenshot from 2021-02-04 18-22-49](https://user-images.githubusercontent.com/36921793/106895600-71231c80-6716-11eb-84f2-347956fcc3b1.png)

- Unable to find an option to assign a dynamic text to tooltip.

![Screenshot from 2021-02-04 18-22-21](https://user-images.githubusercontent.com/36921793/106895713-91eb7200-6716-11eb-9d2d-e3d8cc1082a9.png)

If we prepare json without type definition then above mentioned options are working properly in chart.

**Comment by zingsoftadmin** [comment]
For `behavior` and `tooltip.text` - have updated types in https://github.com/zingchart/DefinitelyTyped
For `scale.items` - Your usage is incorrect. You should be using `item` to style scale items - https://www.zingchart.com/docs/tutorials/elements/scales#scale-items

**Comment by stuurman** [comment]
@zingsoftadmin 
I assumed angular-zingchart already has typings? Why do then additional typings need to be installed? 
Also the documentation does not mention this: [https://www.zingchart.com/docs/integrations/angular](https://www.zingchart.com/docs/integrations/angular)?

**Comment by stuurman** [comment]
> @zingsoftadmin
> I assumed angular-zingchart already has typings? Why do then additional typings need to be installed?
> Also the documentation does not mention this: https://www.zingchart.com/docs/integrations/angular? Or did I overlook it?

@zingsoftadmin polite kick

**Comment by niravIntentlabs** [comment]
> For `behavior` and `tooltip.text` - have updated types in https://github.com/zingchart/DefinitelyTyped
> For `scale.items` - Your usage is incorrect. You should be using `item` to style scale items - https://www.zingchart.com/docs/tutorials/elements/scales#scale-items

Thank you for updating your chart types. I was not mentioning about scale items. I mentioned about the guide in scale items. We want to set multiple style for guide items.
