### ISSUE TITLE
Make zingchart-angular wrapper compatible with Angular 16

### ISSUE THREAD

**Issue by lasabahebwa** [zingchart/zingchart-angular#52]
I can confirm the following error(error NG6002: 'ZingchartAngularModule' does not appear to be an NgModule class) with angular 16. This might require us to update our zingchart-angular wrapper. Please read [here](https://secure.helpscout.net/conversation/2238441285/10823?folderId=6879164) for more customer details.
![a16](https://github.com/zingchart/zingchart-angular/assets/93678483/97235f2a-bbfa-4c30-863b-8a9422700c05)

**Comment by jeanettephung** [comment]
Wrapper is now compatible with Angular 16
