### ISSUE TITLE
chart resize bug

### ISSUE THREAD

**Issue by lasabahebwa** [zingchart/zingchart-angular#54]
In the attached demo, before hitting the resize button, the chart width is responsive according to the browser width. After clicking clicking the resize button, the chart width intermittently stops being responsive(becomes buggy) in relation to the browser width.
![rb](https://github.com/zingchart/zingchart-angular/assets/93678483/f3dbb9d0-4286-44fc-acda-3c9952edbfee)

https://drive.google.com/file/d/1VS5UMw88KnWARgnvue2Ko96kur3xXNB8/view?usp=sharing

**Comment by jeanettephung** [comment]
Waiting for LivingStone to attach of demo outside of Angular to determine if this is an Angular or library bug.

**Comment by jeanettephung** [comment]
Replicated bug outside of Angular: https://app.zingsoft.com/demos/create/GNGGBALX

**Comment by jeanettephung** [comment]
@lasabahebwa Note that the ZingChart-Angular version is 1.0.17.
In the future, the bugs needs to be tested at the latest version.
The bug still persists, so I will fix it in the latest.

**Comment by jeanettephung** [comment]
This bug is occurring outside of Angular.
@lasabahebwa This needs to be refiled as a zingchart-lib bug

**Comment by lasabahebwa** [comment]
This has been refiled as a zingchart-lib bug

**Comment by lasabahebwa** [comment]
This has been refiled as a zingchart-lib bug
