### ISSUE TITLE
Unable to install into Angular 11 project

### ISSUE THREAD

**Issue by mindscratch** [zingchart/zingchart-angular#6]
While trying to install into an Angular 11 project using Node 15.4.0 and NPM 7.0.15, it fails:

```
> npm install zingchart-angular
...
npm ERR! Found: @angular/common@11.0.9
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~11.0.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^8.2.14" from zingchart-angular@1.0.0
npm ERR! node_modules/zingchart-angular
npm ERR!   zingchart-angular@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
```

I was able to reproduce this using a brand new Angular 11 project using Node 15.4.0 and NPM 7.0.15:
```
> ng new zing-test
> cd zing-test
> npm install zingchart
> npm install zingchart-angular # this is where it fails
```

**Comment by stuurman** [comment]
This seems to be a workaround not a fix. 
Also see the error message of npm (version 7.7.4):
_Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution._

When is the library going to be upgraded to just support angular 11 (soon 12 is already coming) and this one is still fixed to Angular 8?

**Comment by angeltg83** [comment]
hey, 
please!!
I need help!!
![err-chart](https://user-images.githubusercontent.com/8096392/119201109-db589680-ba53-11eb-8077-9a2d682b7d12.png)

**Comment by dannyjuergens** [comment]
@angeltg83 This appears to be a network problem, please reference this thread: https://github.com/npm/npm/issues/6820
