### ISSUE TITLE
DefinitelyType ZingChart Angular - Unable to find few options

### ISSUE THREAD

**Issue by niravIntentlabs** [zingchart/zingchart-angular#9]
For behavior and tooltip.text - have updated types in https://github.com/zingchart/DefinitelyTyped

For scale.items - Your usage is incorrect. You should be using item to style scale items - https://www.zingchart.com/docs/tutorials/elements/scales#scale-items

Thank you for updating chart types.

I was not mentioning about scale items. I mentioned about the items in guide in scale-y.

Here is the link I m referering to for JSON :- https://www.zingchart.com/docs/api/json-configuration/graphset/scale-y/guide/items

Inside a items attribute of guide, We can define an array of items to setup mutiple colors . Here is the sample link
https://app.zingsoft.com/demos/embed/325L7V14?_ga=2.124812685.623227439.1621510069-1867824964.1616003215

We are not able to define array of items inside guide of scale. I am using latest typed defination of zingchart as you metinoed.
I also wanted to define a border-radius for each item, which I am able to do it javascript demo.

Here is the link of previous issue - https://github.com/zingchart/zingchart-angular/issues/5

**Comment by niravIntentlabs** [comment]
@zingsoftadmin Gentle reminder if you can share your feedback on above.

**Comment by stuurman** [comment]
@zingsoftadmin could you please provide some feedback on this question. This ticket has already been unanswered for almost four months

**Comment by jeanettephung** [comment]
TDF updated to include missing options and camel-case format of options.
